<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商家管理员管理",
                        "menuJump":"列表",
                        "tableName":"shangjiaguanli"
                    }
                ],
                "menu":"商家管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"销售管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"销售管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"会员管理",
                        "menuJump":"列表",
                        "tableName":"huiyuan"
                    }
                ],
                "menu":"会员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商品管理",
                        "menuJump":"列表",
                        "tableName":"goods"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商品订单管理",
                        "menuJump":"列表",
                        "tableName":"goodsOrder"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商品订单详情管理",
                        "menuJump":"列表",
                        "tableName":"goodsOrderList"
                    }
                ],
                "menu":"商品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"积分商品管理",
                        "menuJump":"列表",
                        "tableName":"jifengoods"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"积分商品兑换管理",
                        "menuJump":"列表",
                        "tableName":"jifengoodsOrder"
                    }
                ],
                "menu":"积分商品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商品种类管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGoods"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商家管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShangjia"
                    }

                ],
                "menu":"基础数据管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"销售管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"销售管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"会员管理",
                        "menuJump":"列表",
                        "tableName":"huiyuan"
                    }
                ],
                "menu":"会员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"积分商品管理",
                        "menuJump":"列表",
                        "tableName":"jifengoods"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"积分商品兑换管理",
                        "menuJump":"列表",
                        "tableName":"jifengoodsOrder"
                    }
                ],
                "menu":"积分商品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商品管理",
                        "menuJump":"列表",
                        "tableName":"goods"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"商品订单管理",
                        "menuJump":"列表",
                        "tableName":"goodsOrder"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"商品订单详情管理",
                        "menuJump":"列表",
                        "tableName":"goodsOrderList"
                    }
                ],
                "menu":"商品管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"商家管理员",
        "tableName":"shangjiaguanli"
    }
	,{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"会员管理",
                        "menuJump":"列表",
                        "tableName":"huiyuan"
                    }
                ],
                "menu":"会员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"商品管理",
                        "menuJump":"列表",
                        "tableName":"goods"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"商品订单管理",
                        "menuJump":"列表",
                        "tableName":"goodsOrder"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"商品订单详情管理",
                        "menuJump":"列表",
                        "tableName":"goodsOrderList"
                    }
                ],
                "menu":"商品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"积分商品管理",
                        "menuJump":"列表",
                        "tableName":"jifengoods"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"积分商品兑换管理",
                        "menuJump":"列表",
                        "tableName":"jifengoodsOrder"
                    }
                ],
                "menu":"积分商品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
	,{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"商品管理",
                        "menuJump":"列表",
                        "tableName":"goods"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"商品订单管理",
                        "menuJump":"列表",
                        "tableName":"goodsOrder"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"商品订单详情管理",
                        "menuJump":"列表",
                        "tableName":"goodsOrderList"
                    }
                ],
                "menu":"商品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"积分商品管理",
                        "menuJump":"列表",
                        "tableName":"jifengoods"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"积分商品兑换管理",
                        "menuJump":"列表",
                        "tableName":"jifengoodsOrder"
                    }
                ],
                "menu":"积分商品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"会员",
        "tableName":"huiyuan"
    }
];

var hasMessage = '';
